### ISSUE TITLE
Concat.py, isn't recognising quotes

### ISSUE THREAD

**Issue by aoifefitz2016** [kieranjol/IFIscripts#210]
Hey, 

I'm running concat.py on a directory that contains a quote in its directory name. Concat.py prompts me to replace the quote with an underscore, but the script stops whether I submit yes or no. 

Thanks, 

Aoife

**Comment by kieranjol** [comment]
Thanks Aoife! Let's sort this one out tomorrow morning either by:
*  Renaming the file/folder and noting the rename in the logfile (which, as you mentioned, will break the existing manifest)
or
* Fix the actual concat code so that it doesn't care about spaces. Probably by just adding an escaping character for the `'` - must test this in both windows and osx as they handle escaping differently.

**Comment by kieranjol** [comment]
P.S - I think this is the culprit actually - https://github.com/kieranjol/IFIscripts/blob/master/ififuncs.py#L550
It's far too simple. If we add escaping in here, all SHOULD be well.

**Comment by kieranjol** [comment]
Hey, so i've tried following the escaping rules here: https://www.ffmpeg.org/ffmpeg-utils.html#Quoting-and-escaping
and I can't get it work on OSX, either in the script or just using `-f concat` on the command line.
I don't want to spend too much more time on this due to:
* so few examples of this occuring
* Us not wanting quotes in filenames to begin with

so until I get a workingmethod of escaping, I might close this and we should look into removing the quote from the folder instead.

Sorry!
