### ISSUE TITLE
makedpx problem

### ISSUE THREAD

**Issue by raecasey** [kieranjol/IFIscripts#218]
I'm having some difficulty with makedpx.py while trying to transcode batches of adverts from tiff to dpx for the iapi event
it worked fine for two batches a few weeks ago, but now it keeps coming up with an error message. 
It happens just after the manifest is created on the first advert in the bunch, - just as it begins to transcode. 
it seems to be a problem with naming in premis.
i'm attaching the error
![screen shot 2017-08-31 at 13 03 46](https://user-images.githubusercontent.com/20825123/29922358-2d51b8e0-8e4d-11e7-8594-04bd945bef6c.png)

**Comment by raecasey** [comment]
i'll be at a meeting for an hour directly after lunch. but the terminal window is open on the macmini if you want to take a look

**Comment by kieranjol** [comment]
I'd imagine that the script is expecting the adverts project filenames
scheme. I'll take a look after lunch.

On 31 Aug 2017 13:07, "raecasey" <notifications@github.com> wrote:

i'll be at a meeting for an hour directly after lunch. but the terminal
window is open on the macmini if you want to take a look

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kieranjol/IFIscripts/issues/218#issuecomment-326275737>,
or mute the thread

**Comment by kieranjol** [comment]
So the issue was that there was no Premis xml in the source directory, so
it couldn't harvest the data required. I think we can close this but feel
free to reopen.
