### ISSUE TITLE
Copyit.py manifest issue - Files within Hidden Directory

### ISSUE THREAD

**Issue by ecodonohoe** [kieranjol/IFIscripts#238]
Hi Kieran,

I'm currently looking at this but thought I'd raise it here in case you had any idea. See pic below:

![copyit_issue](https://user-images.githubusercontent.com/15345230/36210292-ff768b40-1195-11e8-8df7-b0305a8244a5.jpg)

The 2 files in question (.stls), that are being counted for the manifest but not transferred, are found inside a hidden directory which is itself contained in a hidden $RECYCLE.BIN folder.

Copyit appears to have the correct catches in for these directories within the os.walk so unsure why these are still being counted..

If you've any ideas let me know.

**Comment by kieranjol** [comment]
I don't get it either.. https://github.com/kieranjol/IFIscripts/blob/master/copyit.py#L136 has the right catch.. Can we take a look at this tomorrow? Hopefully those files are still present on the drive..

**Comment by ecodonohoe** [comment]
Sure, sounds good. We should be able to reproduce it if needs be.

**Comment by ecodonohoe** [comment]
Note to self. Run update.py everyday!

**Comment by kieranjol** [comment]
Lol

On 15 Feb 2018 2:45 pm, "ecodonohoe" <notifications@github.com> wrote:

Closed #238 <https://github.com/kieranjol/IFIscripts/issues/238>.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/kieranjol/IFIscripts/issues/238#event-1476008025>, or mute
the thread
