### ISSUE TITLE
New script - makezip

### ISSUE THREAD

**Issue by kieranjol** [kieranjol/IFIscripts#244]
It looks like we'll have to use the ZIP or TAR file formats to package part or all of our archival packages before they get written off to preservation storage. We will definitely have to use them for image sequences.

Anyhow - I created a zipfile using python itself and all seemed to go well. There's a benefit to keeping the zip workflow within python as much as possible, rather than relying on installing external tools. Installing and updating tools on multiple operating systems and computers  is a pain and should be avoided where possible.

I then intentionally damaged the zip file in a hex editor by flipping a single bit. 

Using the built in zip extractor in OSX, the zipfile expanded as normal and OSX never flagged that there was a damaged file.

However, using the 'test' function in 7ZIP - it was able to figure out that something was wrong:

```
7za t blaa1.zip 



7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21

p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,12 CPUs x64)



Scanning the drive for archives:

1 file, 2483254 bytes (2426 KiB)



Testing archive: blaa1.zip

--

Path = blaa1.zip

Type = zip

Physical Size = 2483254



ERROR: CRC Failed : metadata/432_4767_01.MP4_mediainfo.xml

                                                 

Sub items Errors: 1



Archives with Errors: 1



Sub items Errors: 1
```

It looks like python itself can also do this testing:
```

>>> with zipfile.ZipFile('blaa1.zip', 'r') as myzip:

...     myzip.testzip()

... 

'metadata/432_4767_01.MP4_mediainfo.xml'
```

btw, even flipping that one bit caused a huge amount of damage to the XML file. Let me now if you want to see the difference.

Anyhow it looks like it should be more straightforward than previously thought to test the validity of ZIP. 

We will need to familiarise ourselves with the ZIP spec - for example it's good to know that all valid ZIPs MUST contain CRC32 checksums  - this is how these tools can check the validity. CRC32 is an 8 character, pretty weak  checksum algorithm. It was able to detect a bitflip though.

So it looks like the way forward for this will be a script that will:

1. Zip a directory (an objects folder, a metadata folder, a whole package - yet to be decided and the script will allow us to make that decision)
2. Log the preservation event and agents in the logfile
3. validate the zip
4. Log the validation event and agents in the logfile

**Comment by mcampos-quinn** [comment]
What's the background on this? Is it in writing sequences to tape?

> Let me now if you want to see the difference.

Yes please!

**Comment by kieranjol** [comment]
Hi!
Here's the work in progress script I knocked up when testing that out - https://gist.github.com/kieranjol/e2bae8ea11444a404d4750943f135512 - I just put it on gist cos it's a bit ugly, i'll tidy it up and merge it into master soon.

Anyhow - this is to do with tape, but it's moreso with our HSM device. We were writing image sequences to a standalone deck using `copyit.py -l` and everything was going great. We could run `validate.py` and all. Writing image sequences to our HSM is a nightmare. Writing them to the spinning disk part of the HSM is fine, it's just the tape robot gets all confused when writing the files to the two LTO tapes. It takes way too long, the internal database becomes super sluggish and difficult to parse through when you suddenly start creating millions of files.
So if we just kept on using a standalone deck (we used USB3, I understand that SAS or thunderbolt would be much faster), we'd be grand, but for various reasons, we wanna use our HSM more.

Anyhow, I'd rather not zip at all, but if we have to, I want to verify losslessness. So I was afraid that for a 2TB sequenced, we'd need 6TB of space available:
* 2TB of original files
* 2TB for the zip (i'd rather not compress, it's crappy enough to have to zip in the first place)
* 2TB for the extracted files in order to do a fixity check to ensure that the zipping was lossless.

Also this would take SO MUCH TIME.

So it looks like the validate function within the python libraries actually is very reliable. I put in the sleep(45) call as it gave me enough time to open the zip in a hex editor and flip a bit, but I could have just pressed `ctrl + z` in order to pause ;)

Anyhow it looks like python only tells you the first corrupted file, but I guess that's enough for me really. I think I can actually trust the validation, though it is crc32 and there is a tiny chance of a collision.. What do you think??

As for showing you the difference, I will tomorrow. It was really interested to see how weird the corruption was..

**Comment by kieranjol** [comment]
btw, I greyed out the output destination., so it just makes your zip in your current working directory. I think @ecodonohoe  might have done a bit of testing with this but I'm not sure.

**Comment by mcampos-quinn** [comment]
Thanks! We have had some trouble with image sequences in the system that we are in the process of abandoning...  We use a dual deck with a SAS connection but indexing all the image files produced a lot of challenges.

What is the HSM you are using? Is it an institutional desire to use it for access purposes? Or 'automating' stuff? 

Oof, all that zipping, unzipping, knitting exciting underwear (`python` reference...). Sounds like a pain. Neat trick to zip in and fiddle with the file as it's being processed!  I have never used the `zipfile` library, cool to know it has built-in verification. I'd agree that knowing that at least one file is corrupted is enough to stop the process and try again. But [here's](https://stackoverflow.com/questions/14210298/probability-of-collision-when-using-a-32-bit-hash/14217471#14217471) a thread on CRC32 collision... Using the formula they provide, if there are ~29,000 frames in a 20 minute 24fps reel that makes for a ~ 0.17 chance of a crc32 collision between any two frames. I'm, uh, not a statistician so maybe check that math. Luckily at UC Berkeley we have an intern who *is* a statistician so I'll ask him this week! It does seem kind of high.

A couple of people here have asked about zipping DPX sequences so I'll keep an eye out to see what you do. Are you still working on the concept of DPX->FFV1? We're also curious about that as a possibility.

**Comment by kieranjol** [comment]
> Thanks! We have had some trouble with image sequences in the system that we are in the process of abandoning... We use a dual deck with a SAS connection but indexing all the image files produced a lot of challenges.
> 

Are those decks linked? Like one command fills up two tapes simultaneously?

> What is the HSM you are using? 
Strongbox 6TB model (i don't have exact model numbers off the top of my head) that links up with Spectra Logic T50 (i think that's the model) LTO tape robot. 

> Is it an institutional desire to use it for access purposes? Or 'automating' stuff?

Well it's more that we have it, and wanna use it cos there's just too much of a logjam if we're relying on a single deck. And this thing can be pretty smart about how it works - like you can queue up loads of jobs, add like ten tapes into the library and walk away. I'm still quite paranoid about it so i'm obsessively checking up on it. I can probably share some internal documentation I've written up on it if interested - might need to get an OK on that first though. Also, this will allow multiple users at once to write to the HSM, and then we can set up different rules based on each user, and the queue system is kinda nice.

> 
> Oof, all that zipping, unzipping, knitting exciting underwear (python reference...). Sounds like a pain. Neat trick to zip in and fiddle with the file as it's being processed! I have never used the zipfile library, cool to know it has built-in verification. I'd agree that knowing that at least one file is corrupted is enough to stop the process and try again. But here's a thread on CRC32 collision... Using the formula they provide, if there are ~29,000 frames in a 20 minute 24fps reel that makes for a ~ 0.17 chance of a crc32 collision between any two frames. I'm, uh, not a statistician so maybe check that math. Luckily at UC Berkeley we have an intern who is a statistician so I'll ask him this week! It does seem kind of high.
> 

OH GOD PLEASE ASK!!! My math is dreadful so i can't make sense of the numbers in that link right now. However, would it be fair to say that it would not matter if two files in an image sequence had the same checksum? With born digital sequences, you'll get loads of those anyhow with purely black frames. Wouldn't the issue be if a damaged file is damaged in such a way that it produces the same hash as the original file? I'd imagine that the odds of that happening are really low - but still..... i don't like the odds. Like the other way to do it is to just unzip and run an md5 check which would probably be doable - maybe a space saving script could:

* extract file 1
* reference md5 manifest and perform fixity check on file 1
* if file 1 is OK - delete file 1
* repeat first three steps for all other files
* if not - print error and sys.exit()

This could be super slow and I'm not sure if it's even possible to extract one file at a time like that. it would save a lot of temporary space though.

> A couple of people here have asked about zipping DPX sequences so I'll keep an eye out to see what you do. Are you still working on the concept of DPX->FFV1? We're also curious about that as a possibility.

We are very much working on DPX-> FFV1. We are waiting for RAWCOOKED to be fully operational. We funded some developments in RAWCOOKED, and the particular 12-bit DPX from Resolve is now supported by ffmpeg/ffv1 <3 - you should check out this thread: https://patchwork.ffmpeg.org/patch/8379/ - some interesting lossless checking in there.

Anyhow, FFv1/MKV is the plan, we just wanna do it responsibly. Though we have a lot of 16-bit TIFF DCDMs that are not supported by FFV1, and the fact that they are born digital makes me a little more reticient to normalise, but I think it's something we'll end up doing. I think @stephenmcconnachie in the BFI is investigating this angle :)

Also we have a whole bunch of RAW BAYER CRI files from the Cintel. In my opinion, these should all be dumped in a fire as they're the most proprietary, inaccessible moving image file format I have ever encountered. I have so many issues with these files and with the latest Cintel update, this whole situtation  got even WORSE from a digital preservation perspective. Anyhow, if we were to preserve these files, zipping would be the way to go for now. debayering is the worst - especially when the free/open workflow uses a sub-standard algorithm compared to the proprietary one in Resolve.

**Comment by kieranjol** [comment]
Edit - the DCDM stuff is probably doable in FFV1 but it wouldn't be super reversible I think. I haven't looked into it too much really. I meant to say though that TIFF/DCDM is not yet supported in RAWCOOKED - it needs a sponsor..

**Comment by stephenmcconnachie** [comment]
>>>I think @stephenmcconnachie<https://url6.mailanyone.net/v1/?m=1f8BU5-0001iL-3o&i=57e1b682&c=C7i7NcOwozoABbKqvJ0Htcdn8limqnINYpDIwCjjopWIUpu7769_g0gIgfbX_Q0vxqH4zgqXiDrLAsNWEfpHo4juRPAbT29tgXlzPosLKutmzvJPXy3jTmzBr5-28tw09N_IU_saUkzroWPCUlO8IYh2u_c0xZ1GMoNnWLYSd2jEyNTiBwqM0X6h3bxSz_xa0tTyOi0tCPykboy0W80sB1Q0aNlx3Q-oCi_NhUb5Etc> in the BFI is investigating this angle :)
Yes, right, hopefully. I’m aiming to engage my firm in contributing to the multifaceted RAWCooked development and I figure DCDM’s TIFFs is a good attack vector.

Sent from my iPhone

On 16 Apr 2018, at 22:21, kieranjol <notifications@github.com<mailto:notifications@github.com>> wrote:


Also, it's this link that has the lossless stuff, not that it mattered much in the end: https://patchwork.ffmpeg.org/patch/7528/<https://url6.mailanyone.net/v1/?m=1f8BZ5-00059e-6M&i=57e1b682&c=e-nJVjNAtmYH7ocg79DJptnY1UWSmpfrkxpFP03yaBSFyDGw0fKM_rvvgv2SKN0feqbW30KvOqHuanK91MfCx553lQ72ggm6E5Q0BjJc5cfMe8fw7J_dzORo3mQk0Hk_fkTL7ViF1kMKbHaUN_VXl7Dl5qYkaexCUNLp5VIC2DNChER9LzUMFoaMifWfzvBdBLxGivZuEWwbAbuYsU9UFhBeA2NId3oQxxNw8XAldNn2G6V1LfP-ANAMdXUVQNd7>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://url6.mailanyone.net/v1/?m=1f8BZ5-00059e-6M&i=57e1b682&c=9gh0mgWAH2L3CgC-Ky1z5KGglN0RBt-GgWIyGZILNwofZx32iSBeAXk6I4vCx-t7mHNXN8D8umVcfNB1Luorf-zX1YZCyEwpZeEWzwk7EUGiUDmNhUmx0JoHuNzzALpkulPmVcBvF48BHb-Qt-NlvYD3c46imAv9UHCkoo54ah6cUN297NmiLoyFUMxu5IqjU1RmXvWtYcp6Z_lXhIHVR34KWh357YbMZrAK6V6FHYi41UNPpUvpef-0oLvcgkB0GFPDATxzQpHl_DlzZ0LoXgRGod8BcJ7qVL7NTzZR-08>, or mute! the thread<https://url6.mailanyone.net/v1/?m=1f8BZ5-00059e-6M&i=57e1b682&c=loUoykUHb61pQ3dmLn7CUhpRzYQx3IUnqe5hdIRzzxM8BEkhWQ0LaA_ZNofeGiN8PCjL8yjC1ZmihDpdRIzGrxS7i2crrdBZ2uK5NgTaiyu-1SsOQi4UbNhfjmPxShqFfTTIBlJEt4axtO40SVCheB58D4M37zaqmD8wq_fXDByKN8BC0OO-HNFAKdsJH1MQVh7Y9Zrxk2EH5qgjoNHQwvl4eJWRVX75wgjSmNnBG6dAkIjYMiu1Ocw5KgBy-1_F3hRY7RGqRjDAwuEUOHoQaEEShihhri8oP-3jfqMvBD2AY6hNI7sr8dDLKl6XW1vBZYQ2Zwx7m1lMyMMQdbxsfw>.

The British Film Institute is governed by Royal Charter and is a charity registered in England and Wales number 287780. The contents of this e-mail are confidential and may be legally privileged. If you are not the intended recipient, kindly notify the sender that you have received this message in error and immediately delete it. Unless you are the intended recipient, you may not forward this e-mail to anybody, nor make any use of its contents.

**Comment by mcampos-quinn** [comment]
Thanks! A lot to process there. Queuing is something we will probably need to consider at some point but our volume is so low that it's not really a concern now. TAPE ROBOT is such a cool term tho. Our decks are physically in the same enclosure, but they are on separate filesystem mount points and need their own read/write commands.... 

I didn't consider born-digital black frames having the same checksum... Yes, I think you're more interested in the before/after collision of a single frame so the odds of that must be much much smaller than simply two frames in a sequence having colliding hashes. Maybe to the point of not being a concern? But I'm totally the wrong person to assess that.

The md5 flow you describe would certainly add some processing overhead. [This post](http://blog.thecodingfrog.com/2009/06/performance-benchmark-of-crc32-md5-and.html) benchmarked md5 at 4x the processing time vs. crc32. 

I have been checking in on RAWCOOKED here and there but I should probably pay more attention. My boss will be at FIAF this/next week so hopefully I can convince her to talk to people about it. There's 0 chance of us funding anything, but we may become a 'subscriber?' We have a hard time buying tape! I will try to make sense of the ffmpeg thread.... Our use cases are so simple that I think we are not going to need a lot of the edge cases.

My condolences on having to work with those CRI files. Luckily our output is pretty clean from the LaserGraphics machine.

**Comment by kieranjol** [comment]
@stephenmcconnachie  and I will also be at FIAF! Who's your boss? We must definitely chat. BTW - part of my talk at the open source panel will be about how a few years ago, we would never have funded anything open source, but our engagement with the community has made it seem like a really good investment.

The ffmpeg thread probably looks more complicated than it is. Carl Eugen Hoyos is sceptical of using framemd5s for losslessness checks - he even questioned me on it in person at No Time To wait in the Q&A section of my presentation <3
So I ran some tests with graphicsmagick's version of 'framesha256' to prove that Jerome's new patch produced identical values to the existing graphicksmagick decoder. I think it was all unnecessary, it would have gotten merged anyhow but I learned something new I guess.

As for the CRI - they really have the potential to be great if they had the support of blackmagic in terms of making them an open, sustainable format. Or that they use CinemaDNG or something (though i know nothing about that). From what I understand, LaserGraphics make great machines and are a good company. I believe that maybe Indiana university, or the smithsonian, or NYPL or someone came close to getting them to support FFV1 as a capture format, but maybe it didn't work out at the very end. Perhaps Lasergraphics know more?

Anyhow thanks for all this - I'd kind of put makezip on the back burner but this discussion has lit a fire in me again about it.

**Comment by mcampos-quinn** [comment]
Cool! My boss is Nancy Goldman. She'll be talking about the future union catalogs I believe. I'll try to convince her to hear your panel!

Neat, I'll ask Carla Arton about the FFV1 story... Yeah the lasergraphics is pretty cool, it has been pretty reliable in the last couple years. We have some gripes but its output is v nice.

I'll keep an eye out here!

**Comment by stephenmcconnachie** [comment]
I’m on the FIAF Cataloguing Commission with Nancy - by the way I sent her the link to the FFV1 / Matroska reading list FIAF published.

Sent from my iPhone

On 17 Apr 2018, at 00:34, Michael Campos-Quinn <notifications@github.com<mailto:notifications@github.com>> wrote:


Cool! My boss is Nancy Goldman. She'll be talking about the future union catalogs I believe. I'll try to convince her to hear your panel!

Neat, I'll ask Carla Arton about the FFV1 story... Yeah the lasergraphics is pretty cool, it has been pretty reliable in the last couple years. We have some gripes but its output is v nice.

I'll keep an eye out here!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://url4.mailanyone.net/v1/?m=1f8Ddh-0007oV-5S&i=57e1b682&c=u-aQv5YAB6ToMQdukXBtDoxnCqXcyo1ENTz_AHpg2daRPq4RvlVDwYhp-b8fep7IcsvIxvkDBtQzrCacOSByk7bAjZ0DIW0PwLOt0ULCZllVq_MA9wYDsmrg3Pyz8DlfabZjE7-rT-WRWY6n6ij0RrefEOp9NNO93MiKmjzGNg0vcBsUntXRnXM7T2N2MlJmYDtS9bhypgJjM-Hny1e1FPON-C4pBFs3hhw5Sq_TG_EOH1_WNJXvi--qQzYic7ZI4zPN2xwA8vcRfhdxK3_lJVHGKewphF3fmLUrUBYV9Fs>, or mute the thread<https://url4.mailanyone.net/v1/?m=1f8Ddh-0007oV-5S&i=57e1b682&c=aQWeACVfgiN-e54VHzUNs7xebRrK8kZnkhLBuTU_J1m3Qc5_TA5a5odQlvA8R31oUVdUJ2iyYb18TGdZN3OYSW13glmmIkWDUBj_rgtNezXDbJGxpSJfHMoTi1lyXw3X7FfzFGWElt-yN0EEe65pIshndlwHm4wIV2IglU7JTJBpUfrEPG5-az3p_Q_-sc3tPCOkqyLU6HrrGdMfhm2eVtTwM3q6FjR9HmkJWEJU-LJ5bFCxeRmvwfq_E4jjEV9d5XELqVfqj39njHXeVGxuIv3x27sVatc_ybAdPymMtvJHS1wI3JQuFf4U0S0WdYCWg3ftMABJx5y19HMzYC8TbQ>.

The British Film Institute is governed by Royal Charter and is a charity registered in England and Wales number 287780. The contents of this e-mail are confidential and may be legally privileged. If you are not the intended recipient, kindly notify the sender that you have received this message in error and immediately delete it. Unless you are the intended recipient, you may not forward this e-mail to anybody, nor make any use of its contents.

**Comment by kieranjol** [comment]
Ah!it's a small world!

**Comment by mcampos-quinn** [comment]
I asked our statistics major intern about the collisions using CRC32 and his answer was simple and made sense. The probability of a file and a corrupted version of that file having the same hash calculated by CRC32 is just 1 out of the total number of possible hashes the algorithm can make: so 1/2^32 = 1 out of 4,294,967,296.  

Seems safe enough!

MD5 in comparison would be 1/2^128, which I don't even know how to write out.... 3.4028236692093846 10^38

**Comment by kieranjol** [comment]
Ah god thank you so much! If you're happy and your statistician is
happy,then I'm happy!

**Comment by kieranjol** [comment]
ok, so this can be closed - makezip is doing well for a while now..
