### ISSUE TITLE
new script - discreet corner watermark

### ISSUE THREAD

**Issue by raecasey** [kieranjol/IFIscripts#264]
Hi

can we write a new script that puts a discreet IFI watermark on the top right hand corner? this is for copyright holder requests or non-commercial access, - where we waive the fees in return for visual credit.
the arguments would be - to keep the same format; change to pro res hq.mov or change to h264.mov
the watermark would be the ifi logo in white.

cheers
R

**Comment by kieranjol** [comment]
Cheers Raelene, Let me know if this is a priority or if it can be done after the accessioning push.

**Comment by raecasey** [comment]
yes, - after the accessioning push

thanks

**Comment by raecasey** [comment]
hey, - is this a quick script?
would it be possible to get it done early next week?
Manus wants to get a file to a copyright holder next week, but i'm reluctant to give it without a watermark.
it would basically be the same as the ifi player. the ifi logo in the top right hand corner, a little smaller and much lower opacity, so that it's just at the point where it's readable.
let me know if you don't think you can get it done next week and i'll let Manus know
cheers
R

**Comment by kieranjol** [comment]
I'll take a look on reception here and see how quick it might be.

**Comment by kieranjol** [comment]
Hey, so no script right now does the logo overlay. Aaron manually adds that himself as far as I know. 
It looks like I added this to ffmprovisr a while back based on the research I was doing for Aaron - https://amiaopensource.github.io/ffmprovisr/#image_watermark

Just to confirm, is this script idea for an image sequence or for a video file?

I could add an argparse option to bitc, that places the logo in the top right hand corner? Rather than makng a brand new script. I could try that out this week and see how easy it is. To be honest, prores.py should be merged with bitc.py cos they're both doing the exact same thing. It could be called something else other than bitc, like `makeaccess`or something, which i think is what CUNY/mm does.

Can you provide me with the IFI logo that you'd like to use? It will have to be the transparent PNG that Aaron uses.

Also we could just add the ifi logo as a file to the git repository, or the `-logo` option could take the path of a logo, so it would leave it flexible.
This command line would look something like:
`bitc.py -logo path/to/player_logo.png path/to/video_file.mov`

**Comment by raecasey** [comment]
hi
and 6 months later...
i've been looking into this. I got a bunch of pngs off Daniel and have been trying to do this myself using ffmpeg and following your instructions on ffmprovsr:

 I can get it working for the non transparent png that daniel provided me with, but i can;t get it workign for what should be the transparent png. I've about 15 or 20 sd quicktimes that i need to give to a copyright holder. The non-transparent logo is not discreet enough. Can you help me?

cheers
R

**Comment by kieranjol** [comment]
Yes, I've no idea how to do it to be honest but I can give it a go. Maybe you can show me in person what you tried and we can take it from there?

**Comment by kieranjol** [comment]
btw, using this transparency - https://www.fnordware.com/superpng/straight.png
I was able to get the ffmprovisr command to work:
`$ ffmpeg -i input_video.mov -i straight.png -filter_complex overlay=main_w-overlay_w-5:5 output_file.mov`
 
![out](https://user-images.githubusercontent.com/1127102/49539556-cb6d8c00-f8c5-11e8-9e66-8ccca6b3a58c.jpeg)

**Comment by kieranjol** [comment]
Ok, so i just remembered something. I think Daniel's png files might be absolutely massive, like 4K size. I think the ffmprovisr command is not doing any scaling, so your command was probably fine, it just was a 4K image that was overlaid on SD PAL, so you just couldn't see it as there might have been empty space in the bit of the logo that overlaid 720x576.
I just rescaled an IFI logo I had in my email and then the command worked just fine.
![out](https://user-images.githubusercontent.com/1127102/49540068-0c19d500-f8c7-11e8-8e59-3b5481e8ccd0.jpeg)
![out](https://user-images.githubusercontent.com/1127102/49540084-150aa680-f8c7-11e8-896e-e3da2168f903.png)

^^ There's the png btw.

**Comment by kieranjol** [comment]
https://github.com/kieranjol/IFIscripts/commit/088c7258fcf59be656a50892b3d065cc4d867b9e
So I've added this here^ 
there is now a `-logo` option. I have also included the small transparent logo in ifiscripts itself. it's call `ifi_logo_small.png`

This is when just using `-logo path/to/logo.png`
![bitc](https://user-images.githubusercontent.com/1127102/49542133-9a448a00-f8cc-11e8-9cc3-e9e666dc29a7.jpg)

and this is with `-logo path/to/logo.png -clean`
![clean](https://user-images.githubusercontent.com/1127102/49542134-9add2080-f8cc-11e8-815d-7d2b812f6c83.jpg)

**Comment by kieranjol** [comment]
BTW this will only appear nicely for SD input. Coming up with a way to have the watermark scale seems to be quite awkward. Instead, we can just come up with a few watermarks to use for SD, HD, 2K, UHD which should short most workflows internally.

**Comment by raecasey** [comment]
hey

thanks for this and for explaining everything about the size of the file. All makes perfect sense now why it hadn't been working for me. I don't know how you figured it out. 
The logo still isn't transparent enough for me and i couldn't figure out how to make it even more transparent so i resized it again to make it smaller and more discreet. Works well now.
I'll show it to you. 
thanks again

R
