### ISSUE TITLE
validate.py - TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by digitensions** [kieranjol/IFIscripts#324]
Hi,

Been trying to validate.py some checksum .md5 files generated by manifest.py, using python3 on MacOS.  Received the following complaints from Terminal:

MACE2:ifiscripts mac2$ python3 ./validate.py /Users/mac2/Desktop/A0052A_ProRes_manifest.md5
Traceback (most recent call last):
  File "./validate.py", line 205, in <module>
    main()
  File "./validate.py", line 200, in main
    manifest = check_manifest(args.input, log_name_source)
  File "./validate.py", line 135, in check_manifest
    manifest_dict, missing_files_list = parse_manifest(manifest, log_name_source)
  File "./validate.py", line 38, in parse_manifest
    checksum = entries.split(' ')[0]
TypeError: a bytes-like object is required, not 'str'

Subsequently started copyit.py and it's recognised the md5 manifest and started the transfer of directory. Don't think I'll be successful in seeing if it validates as off home shortly and I'm sure the connection will drop out again before completion. But if successful I'll let you know.

Thanks, Joanna

**Comment by kieranjol** [comment]
Thank you,this should be a simple fix I think.

**Comment by kieranjol** [comment]
Hmmm, so I think your version of ifiscripts is quite out of date. Can you run
`git pull`
when in the ifiscripts directory, then try again? The last time line 38 contained `checksum = entries.split(' ')[0]` was back in this version https://github.com/kieranjol/IFIscripts/blob/a86eb9d7f44b4291222b3e115a499b0e41d6b802/validate.py but there has been 4 commits since the, including a python3 fix.. https://github.com/kieranjol/IFIscripts/commits/master/validate.py 

However I did notice that manifest.py -s is now a bit broken in python3 so that's a different fix..
