### ISSUE TITLE
accession_register.py fail

### ISSUE THREAD

**Issue by raecasey** [kieranjol/IFIscripts#370]
this script fails on ES1, ES2 and macmini.
using a fresh filmographic export that worked ok with the batch accessioning job that this is for.
Terminal out put below

R
Last login: Wed Feb  5 14:45:37 on ttys003
ifi-mac-pro:~ admin$ accession_register.py -h
usage: accession_register.py [-h] [-sorted_csv SORTED_CSV]
                             [-pbcore_csv PBCORE_CSV] [-filmo_csv FILMO_CSV]

Generates a helper accessions register. Written by Kieran O'Leary.

optional arguments:
  -h, --help            show this help message and exit
  -sorted_csv SORTED_CSV
                        Path to sorted helper CSV
  -pbcore_csv PBCORE_CSV
                        Path to technical/PBCore CSV.
  -filmo_csv FILMO_CSV  Path to Filmographic CSV. Must contain reference
                        numbers.
ifi-mac-pro:~ admin$ accession_register.py -sorted_csv /Volumes/imports_ingests/ifa_material/film/register_csvs/register_2020-02-03T14_16_09_sorted.csv -pbcore_csv /Volumes/imports_ingests/ifa_material/film/register_csvs/2020-02-03T19_00_27_pbcore.csv -filmo_csv /Volumes/imports_ingests/ifa_material/film/register_csvs/filmo_csv_rc_20200203.csv 
Traceback (most recent call last):
  File "/Users/admin/ifigit/ifiscripts/accession_register.py", line 91, in <module>
    main(sys.argv[1:])
  File "/Users/admin/ifigit/ifiscripts/accession_register.py", line 69, in main
    if filmographic_record['Title'] == '':
KeyError: 'Title'
ifi-mac-pro:~ admin$

**Comment by kieranjol** [comment]
Cheers raelene, this is a python 3 thing. I have a workaround, but I can't
fix this in the scripts until we completely switch over to genie plus csvs,
rather than using older dB text works ones.
I think gavin is the last user that was using dB text works csvs, and
seeeing as he needed to get a new csv recently, perhaps this is the moment
where we only support genie plus?
It would make the ifb bai workflow a lot easier too as we would avoid a csv
editing step as a result.

**Comment by kieranjol** [comment]
btw, this is actually less of a python3 thing and it's more of a genieplus thing - the key fields are called something else in GeniePlus than in DB Textworks - so the error there:
```
if filmographic_record['Title'] == '':
KeyError: 'Title'
```
So this is the main issue. The workaround is to manually change these filmographic headings:

```
Accession_register needs some changes to filmographic:
1. Title/name changes to Title
1. Filmographic URN changes to Reference Number
1. Series Title changes to TitleSeries
1. Episode No changes to EpisodeNo
```

but the longer term solution, one we drop DB TEXTWORKS CSV support, is for the script to look for the modern GeniePlus terms

**Comment by raecasey** [comment]
cool - yes i think we're ready to completely switch over whenever you are.
Gavin has the knack of cretaing new filmo csvs so won't miss the
dbtextworks ones
i haven't been using the dbtextwork ones either
R

**Comment by raecasey** [comment]
but in the meantime, - i'll change those things manually when i get that response again.

**Comment by kieranjol** [comment]
Thanks Raelene - i'm installing all the bits and bobs necessary to get the scripts and tools up and running on my new laptop. THis is a super slow process that takes many hours but I'll work in a proper fix once I am up and running.

**Comment by kieranjol** [comment]
Hi Raelene - this autoclosed with that commit, but instead of manually changing the CSV, can you run update.py, cos I think I've fixed it at a script level. If you're happy, then I'll send around an email to folks and let them know that Genieplus is now only supported. I think i have to change a few other scripts too, probably batchaccession as that needs a small edit too.

**Comment by kieranjol** [comment]
This was tested and all seems well!
