### ISSUE TITLE
move.py - source drive permissions for writing manifests

### ISSUE THREAD

**Issue by ecodonohoe** [kieranjol/IFIscripts#62]
With the possibility of some source drives not allowing manifests to be written to them it is suggested that the destination for these files should be somewhere on the desktop.

**Comment by kieranjol** [comment]
I agree, writing the source manifest to the drive (and the log) seemed like a good idea at the time - but it should be written elsewhere. I'm thinking Desktop/move_logs or something.

So what needs to be done:
1. Check if Desktop/move_logs exists
2. If not, create it
3. Write source manifest and whatever else to that directory
4. make sure that python can find the source manifest so that it can do the diff comparison

i probably won't get to this for a bit so feel free to have a stab at it.

**Comment by kieranjol** [comment]
fixed sort of in https://github.com/kieranjol/IFIscripts/commit/1e3393ff508c7202bfdadb092725b2c3f8871381
I didn't create the logs dir though, everything will be saved to desktop. I or someone can add the log directory later, this will be a temp workaround anyhow. Thanks for reporting!! :+1: :beers:

**Comment by kieranjol** [comment]
Closing as the logs dir has been implemented.
