### ISSUE TITLE
Cant select directory only as source

### ISSUE THREAD

**Issue by AnjaMahler** [kieranjol/IFIscripts#71]
DCDMs are often just in audio&video folder without subfolder. eg E:/video/tiff tiff tiff and  E:/ audio/ wav wav. To select E:/ as  source would be great.

**Comment by kieranjol** [comment]
Thanks for raising this Anja. I'll have to double check but I think this is because  of this line: https://github.com/kieranjol/IFIscripts/blob/master/move.py#L31

Hopefully it's an easy fix. It's looking for the parent folder, but there isn't anything more parental than th root of the drive :(

**Comment by kieranjol** [comment]
Yup, `dirname` and `relative_path` produce no value at all when transfering from the source of a drive. I'll get onto this tomorrow morning.

**Comment by kieranjol** [comment]
Hi, so the real issue, as far as I can tell, is how the source manifest is geneated. 
it firstly uses `cd` to go to the parent directory. Unfortunately, there is no parent, so you end up with an error. I need to change the script so that if the root of a drive is the source, then the manifest is written to the root of the drive.

**Comment by AnjaMahler** [comment]
okay great! Dankeschoen!

**Comment by kieranjol** [comment]
uh, I meant that if the root of a drive is the source, the manifest is run from the root, like
```
cd /Volumes/FAT32
md5deep -ler *
```

instead of what it's trying to do, which is impossible:
```
cd /Volumes/
md5deep -ler FAT32
```
