### ISSUE TITLE
move.py needs to be renamed - suggestions?

### ISSUE THREAD

**Issue by kieranjol** [kieranjol/IFIscripts#72]
move is a system command on windows, and with the changes to IFIscripts that allow us to update the scripts easier, this is suddenly an issue. 

mover.py would work..

**Comment by kieranjol** [comment]
ping @raecasey @briancash  @AnjaMahler @ecodonohoe

**Comment by raecasey** [comment]
mover.py sounds good to me.
however, - are we going to break this up into different scripts because of the size of some of the files, for example the DCDMs?.
i.e. a microservice for creating source manifest, another for moving and another for destination manifest and then a 4th, - already existing - with all three for the smaller files.
I'd suggest:
sourcemanifest.py
destinationmanifest.py
copy.py -(do we even need a script for this? would the gcp command or robocopy be enough?)
and then mover.py for the whole thing

what do you think?

R

**Comment by briancash** [comment]
mover.py seems pretty straight forward and apt

B

**Comment by kieranjol** [comment]
Hi,

Looks like `mover.py` is looking good so? 

Anja raised a similar issue here: https://github.com/kieranjol/IFIscripts/issues/70

I'm in favour of adding an option to move.py, like `move.py -quick` or something, that only did source manifest and copy. If we teach mover.py to be smarter, it should be able to detect that you have a source manifest, and you've moved your files, so now it just needs to create a destination manifest and compare it to the source one. It could even ask a question to the user (Yes/No/Quit) to see if it should just do the destination manifest generation and comparison. We could also do `mover.py -nocopy` which would only do source manifest.

We should definitely have a general manifest.py - which i think would serve the same purpose as source_manifest.py? 

It should be easy to break everything up into seperate scripts as well. destinationmanifest.py would only work reliably if the source_manifest.md5 was always available for access. Unless the source manifest was on a network, you'd have to run the destinationmanifest script on the same computer, as right now, the manifests are saved to the desktop.

**Comment by raecasey** [comment]
cool - yes, - i'd seen Anja's request, - which is why I mentioned it.
all sounds good, - but is a lot of work, so lets 
yes you're right, manifest.py would be the same as sourcemanifest.py (so no need for the source part) 
the idea of a standalone manifest comes back again to what we're looking at in fixity for BAI project. In the middle of writing an email to you about that. We need to think about sha512 as well as md5.

R

**Comment by kieranjol** [comment]
Cool, looking forward to the email.

**Comment by AnjaMahler** [comment]
Cool! mover.py  or moveit.py

**Comment by kieranjol** [comment]
moveit.py!!!!!! This is much sassier, and I think sass should be a deciding factor.

**Comment by briancash** [comment]
ha, I think 'moveit' takes it.....though it may cause a certain 90s dance song to get stuck in your head each time you run it.

**Comment by kieranjol** [comment]
my vote's for moveit.py anyhow. :+1:  :dancer:  :dancers:  :musical_note:

**Comment by AnjaMahler** [comment]
Makes you wanna move move it ;)

**Comment by AnjaMahler** [comment]
Makes you wanna move it move it :)

**Comment by raecasey** [comment]
https://www.youtube.com/watch?v=Dyx4v1QFzhQ

**Comment by kieranjol** [comment]
lolz

**Comment by kieranjol** [comment]
renamed to moveit.py
